name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Publish to maven local
        run: ./gradlew publishToMavenLocal

      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Setup Ollama
        run: |
          sudo systemctl stop ollama
          ollama serve &
          ollama -v
          ollama pull qwen3:0.6b

      - name: Download mcp server sample and run it
        run: |
          git clone https://github.com/modelcontextprotocol/kotlin-sdk.git
          cd kotlin-sdk
          git checkout 0.5.0
          cd samples/kotlin-mcp-server
          ./gradlew build
          java -jar build/libs/kotlin-mcp-server-0.1.0.jar &

      - name: Build integration test project
        working-directory: samples/integ-test-ollama
        run: ./gradlew build

      - name: Run on local mcp server
        working-directory: samples/integ-test-ollama
        run: java -jar build/libs/integ-test-ollama.jar http://localhost:3001 'Call my tool named kotlin-sdk-tool pelase /nothink'

      - name: Run on remote mcp server
        working-directory: samples/integ-test-ollama
        run: java -jar build/libs/integ-test-ollama.jar https://mcp-for-next-js.vercel.app 'Call my tool, you should echo "Hello World" /nothink'

  build-samples:
    strategy:
      matrix:
        sample: [android-ollama, cli-anthropic]
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish to maven local
        run: ./gradlew publishToMavenLocal

      - name: Build with Gradle
        working-directory: samples/${{ matrix.sample }}
        run: ./gradlew build
